### ISSUE TITLE
 translation issue 

### ISSUE THREAD

**Issue by skywateryang** [apachecn/feature-engineering-for-ml-zh#17]
Firstly many thanks to the author for sharing  all the whole chinese translation of this book with great effort paid.

However still something got not quite comfortable on the translation.
I just picked up 2 chapters to read up to now and found some of sentences seem to be done by inferior translating apps.

To illustrate by one example,  one paragraph in 'Bin counting' part in chapter 7 was given by author as 'bin-counting的想法非常简单：而不是使用分类变量作为特征，而不是使用条件概率的目标在该价值下。 换句话说，而不是编码的身份分类值，计算该值和该值之间的关联统计量我们希望预测的目标。'. While actuallly the original text is 'The idea of bin counting is deviously simple: rather than using the value of the cate‐
gorical variable as the feature, instead use the conditional probability of the target
under that value. In other words, instead of encoding the identity of the categorical
value, we compute the association statistics between that value and the target that we
wish to predict.'  It's obviously this kind of issue cannot be made by the people, which can only be explained by inferior apps and the author did not look through it clearly.

I am writing it only to remind author of that, maybe you were busy and neglected the translation issue.

BR

**Comment by feng-1985** [comment]
机器翻译的

**Comment by wizardforcel** [comment]
建议提交 pr，共同维护，谢谢。
